() => {
 const g=window.__webswing,results=[];
 const assert=(v,m)=>{if(!v)throw Error(m)},dist=(a,b)=>Math.hypot(...a.map((v,i)=>v-b[i]));
 const check=(name,fn)=>{try{results.push({name,pass:true,detail:fn()})}catch(e){results.push({name,pass:false,error:String(e)})}};
 const fresh=(mode='FLOW')=>{g.start();g.manual(true);g.settings.sound=false;g.setSwingMode(mode);return g;};
 function fixture(){fresh('MANUAL');const b=g.buildings.find(b=>!b.base&&b.x>20&&b.x<100&&b.z>25&&b.z<70&&b.h>30);assert(b,'fixture missing');const wall=b.x-b.w/2;g.setPosition([wall-.70,25,b.z-b.d/2+2],[.8,0,26]);return{b,wall};}
 function onscreenHit(){g.render();const W=innerWidth,H=innerHeight;for(let y=.20;y<.58;y+=.06)for(let x=.09;x<.92;x+=.07){const a=g.pickScreen(W*x,H*y);if(a&&g.surfaceAnchorValid(a,135))return {a,x:W*x,y:H*y};}return null;}
 check('stick input moves the character rather than choosing an anchor side',()=>{const points=[];for(const x of[-1,0,1]){fresh();g.input.x=x;g.refreshTarget();assert(g.aim.target,'missing auto target');points.push([...g.aim.target.p]);}assert(points.every(p=>dist(p,points[1])<1e-6),'stick directly snaps aim');return points;});
 check('stick vertical axis powers motion without moving an aim cursor',()=>{const points=[];for(const y of[-1,1]){fresh();g.input.y=y;g.refreshTarget();points.push([...g.aim.target.p]);}assert(dist(points[0],points[1])<1e-6,'Y changes target height directly');});
 check('up-stick still increases progressive reeling',()=>{const a=[];for(const y of[0,-1]){fresh('MANUAL');g.attach();g.input.web=true;g.input.y=y;a.push(g.reelValue());}assert(a[1]>a[0]+.4,'power control lost');return a;});
 check('predictive auto aim uses real unobstructed surfaces and rejects empty worlds',()=>{fresh();const a=g.refreshTarget();assert(a&&g.surfaceAnchorValid(a),'invalid surface');assert(g.predictAnchor(a,g.aim.intent)<10000,'predicted collision');g.clearWorld();g.refreshTarget();assert(!g.aim.target&&!g.attach(),'invisible anchor');});
 check('auto-catch and release do not teleport or inject velocity',()=>{fresh();const p=[...g.P.p],v=[...g.P.v];assert(g.attach(),'no catch');assert(dist(p,g.P.p)<1e-9&&dist(v,g.P.v)<1e-9,'catch snap');g.release();assert(dist(v,g.P.v)<1e-9,'release boost');});
 check('CSS screen ray matches the rendered surface point',()=>{fresh();const hit=onscreenHit();assert(hit,'no tappable point');const screen=g.project(hit.a.p);assert(Math.hypot(screen[0]-hit.x,screen[1]-hit.y)<1.2,'ray and projection disagree');return{tap:[hit.x,hit.y],surface:hit.a.p};});
 check('tap replaces an active rope at the exact hit with momentum preserved',()=>{fresh();g.input.web=true;g.attach();const hit=onscreenHit();assert(hit,'no surface');const p=[...g.P.p],v=[...g.P.v];assert(g.fireTap(hit.a,hit.x,hit.y),'tap failed');assert(g.P.rope.source==='tap'&&dist(g.P.rope.a,hit.a.p)<1e-9,'wrong tap anchor');assert(dist(p,g.P.p)<1e-9&&dist(v,g.P.v)<1e-9,'tap snap');assert(g.input.web,'tap cancelled held WEB');});
 check('invalid sky and distant taps never detach an active rope',()=>{fresh();g.attach();const rope=g.P.rope;assert(!g.fireTap(null,50,50),'sky accepted');assert(g.P.rope===rope,'sky dropped rope');const a=g.refreshTarget();assert(a,'target');const far={...a,p:[a.p[0],a.p[1]+500,a.p[2]]};assert(!g.fireTap(far,80,80),'distant accepted');assert(g.P.rope===rope,'distant dropped rope');});
 check('targeted swing is not silently replaced by auto aim or stick movement',()=>{fresh();const a=g.refreshTarget();assert(g.fireTap(a,100,100),'tap');g.input.web=true;g.input.x=.6;const point=[...g.P.rope.a];g.step(42);assert(g.P.rope&&g.P.rope.source==='tap'&&dist(point,g.P.rope.a)<1e-6,'tap override lost early');});
 check('a single tap completes one arc without enabling permanent auto-chain',()=>{fresh();const a=g.refreshTarget();assert(g.fireTap(a,100,100),'tap');const count=g.stats.swingCount;g.step(360);assert(!g.input.web,'tap latched WEB input');assert(g.stats.swingCount===count,'tap secretly auto-chained');assert(!g.P.rope,'targeted arc never released');});
 check('holding WEB resumes automatic swings after the tapped arc',()=>{fresh();g.input.web=true;const a=g.refreshTarget();assert(g.fireTap(a,100,100),'tap');g.step(1800);assert(g.state==='playing'&&g.stats.swingCount>7,'flow did not resume');return{distance:g.stats.distance,swings:g.stats.swingCount};});
 check('persistent targeting line and cursor are removed',()=>{fresh();g.render();assert(document.getElementById('aimTarget').hidden,'old aiming cursor visible');});
 check('glancing near-facade motion enters a wall run',()=>{const {wall}=fixture();g.step(18);assert(g.P.wall,'wall run missing');assert(g.P.p[0]<wall-.40,'inside wall');assert(g.P.v[2]>23,'momentum lost');return{position:g.P.p,age:g.P.wall.age};});
 check('head-on impacts do not become wall runs or tunnel',()=>{const {b,wall}=fixture();g.setPosition([wall-5,25,b.z],[2000,0,0]);g.step();assert(!g.P.wall,'head-on became run');assert(g.P.p[0]<=wall-.399&&Math.abs(g.P.v[0])<.01,'tunnelled');});
 check('wall runs require speed, height and a real wall',()=>{let {wall,b}=fixture();g.setPosition([wall-.7,25,b.z],[0,0,2]);g.step();assert(!g.P.wall,'slow wall run');g.setPosition([wall-.7,2,b.z],[0,0,28]);g.step();assert(!g.P.wall,'ground-level wall run');g.setPosition([wall-.7,b.h+4,b.z],[0,0,28]);g.step();assert(!g.P.wall,'rooftop/sky run');g.clearWorld();g.step();assert(!g.P.wall,'invisible wall');});
 check('wall runs use stamina and exit at a facade edge',()=>{fixture();g.step(20);assert(g.P.wall,'no run');const before=g.stats.energy;g.step(25);assert(g.stats.energy<before,'wall run free energy');g.step(350);assert(g.wallControl.exits>0&&!g.P.wall,'never left facade');return{runs:g.wallControl.runs,exits:g.wallControl.exits};});
 check('steering away peels off the wall with a re-entry cooldown',()=>{const {wall}=fixture();g.step(24);assert(g.P.wall,'no run');g.input.x=1;g.step();assert(!g.P.wall&&g.P.v[0]<0,'did not peel away');assert(g.wallControl.cooldown>.6,'missing cooldown');g.step(15);assert(!g.P.wall&&g.P.p[0]<wall-.9,'sticky re-entry');});
 check('tapping another facade exits a wall run and preserves momentum',()=>{fixture();g.step(20);assert(g.P.wall,'no run');const a=g.refreshTarget();assert(a&&g.surfaceAnchorValid(a,135),'no exit anchor');const p=[...g.P.p],v=[...g.P.v];assert(g.fireTap(a,90,90),'tap exit');assert(!g.P.wall&&g.P.rope.source==='tap','transition failed');assert(dist(p,g.P.p)<1e-9&&dist(v,g.P.v)<1e-9,'wall-tap teleported');});
 check('wall jump via trick breaks adhesion and buffers no stale action',()=>{fixture();g.step(20);assert(g.P.wall,'no wall');g.trick();assert(!g.P.wall&&g.P.flip,'wall jump trick failed');assert(g.P.v[0]<0,'no outward jump');});
 check('pausing freezes the wall run and clears pending scene taps',()=>{fixture();g.step(20);g.tapControl.id=99;g.tapControl.down={};g.pause();const age=g.P.wall.age,p=[...g.P.p];g.step(100);assert(g.P.wall.age===age&&dist(g.P.p,p)===0,'paused wall moved');assert(g.tapControl.id===null,'pending tap survived pause');g.resume();g.step();assert(g.P.wall,'resume lost wall');});
 check('wall-run animation preserves limb lengths and finite hand geometry',()=>{fixture();g.step(36);assert(g.P.wall,'run ended');g.render();for(const a of g.character.armLengths)assert(Math.abs(a[0]-.307)<1e-5&&Math.abs(a[1]-.302)<1e-5,'arm stretch');for(const a of g.character.legLengths)assert(Math.abs(a[0]-.436)<1e-5&&Math.abs(a[1]-.433)<1e-5,'leg stretch');assert(g.character.hands.every(h=>h.tips.length===5&&h.tips.every(p=>p.every(Number.isFinite))),'bad hands');assert(g.character.triangles<5000&&g.stats.glError===0,'mesh error');return{triangles:g.character.triangles,up:g.P.pose.up};});
 check('wall transitions blend pose goals rather than resetting them',()=>{fixture();g.step();const before=g.rig.arms.map(a=>[...a]);g.step();assert(Math.max(...g.rig.arms.map((a,i)=>dist(a,before[i])))<.24,'wall pose snapped');g.input.x=1;g.step(25);assert(g.rig.arms.every(a=>a.every(Number.isFinite)),'exit pose invalid');});
 check('restart clears manual tap and wall-run ownership',()=>{fixture();g.step(10);g.tapControl.feedback={p:[1,2,3],age:0};g.start();assert(!g.P.wall&&!g.tapControl.feedback&&g.tapControl.id===null&&g.wallControl.runs===0,'stale traversal state');});
 check('ground contact remains fatal with wall assistance enabled',()=>{fresh();g.setPosition([0,1.08,48],[0,-8,20]);g.clearWorld();g.step(20);assert(g.state==='dead','ground no longer fatal');});
 check('long tap lines do not shorten to the old 100m limit on the first tick',()=>{fresh();const a=g.buildings.map(b=>({b,p:[b.x-b.w/2-.04,Math.min(b.h-.4,g.P.p[1]+120),Math.max(b.z-b.d/2+.5,Math.min(b.z+b.d/2-.5,g.P.p[2]))],side:-1})).find(a=>g.surfaceAnchorValid(a,135)&&dist(a.p,g.P.p)>108);assert(a,'no long-line fixture');const before=[...g.P.p];assert(g.fireTap(a,50,50),'long tap failed');const length=g.P.rope.length;g.step();assert(dist(before,g.P.p)<1.5,'long-line catch snapped');assert(g.P.rope&&g.P.rope.length>107,'line clamped to old limit');return{length,firstTickTravel:dist(before,g.P.p)};});
 check('pausing a tap-only swing does not secretly enable auto-chain',()=>{fresh();g.fireTap(g.refreshTarget(),100,100);assert(!g.input.web,'initial input');g.pause();g.resume();assert(!g.input.web&&g.P.rope?.source==='tap','pause converted one-shot to auto-chain');});
 check('active wall geometry survives a floating-origin rebase',()=>{fresh('MANUAL');g.setPosition([3456,35,3456],[0,0,26]);const b=g.buildings.find(b=>!b.base&&b.x>3476&&b.x<3556&&b.z>3481&&b.z<3526&&b.h>40);assert(b,'far wall fixture');const wall=b.x-b.w/2;g.setPosition([wall-.70,25,b.z-b.d/2+2],[.8,0,26]);g.step(12);assert(g.P.wall,'no far wall run');const gap=(g.P.p[g.P.wall.axis]-g.P.wall.face)*g.P.wall.sign;g.rebase();assert(g.P.wall,'wall lost on rebase');const after=(g.P.p[g.P.wall.axis]-g.P.wall.face)*g.P.wall.sign;assert(Math.abs(gap-after)<1e-6,'wall moved relative to body');g.step();assert(g.P.wall,'rebased wall failed bounds');});
 fresh();g.input.web=true;g.attach();g.step(120);g.render();return results;
}
